NOMBRE_DSD: DSD_CONTPROV
categoria: ECO_ACCOUNTS
grupos_consultas:
  Contabilidad Provincial Anual de Andalucía. Revisión estadística 2019:
    id: '1'
    consultas:
    - '32118'
variables:
- TERRITORIO
- SECC_CNAE09
- OBS_STATUS
- TEMPORAL
- MACROMAG_CPA
- INDICATOR
- OBS_VALUE
- FREQ
