NOMBRE_DSD: DSD_PADRON
categoria: POP_MIGRATION
grupos_consultas:
  Población por edad simple y provincias según nacionalidad (española/extranjera) y sexo:
    id: '1'
    consultas:
    - '64582'
    - '64703'
    - '64704'
    - '64705'
    - '64706'
  Población por grupos quinquenales de edad y relación entre el lugar de residencia y el lugar de nacimiento según sexo:
    id: '2'
    consultas:
    - '64585'
    - '64773'
    - '64774'
    - '64775'
    - '64776'
  Población extranjera por país de nacionalidad y provincias según grupos quinquenales de edad y sexo:
    id: '3'
    consultas:
    - '64623'
    - '64707'
    - '64708'
    - '64709'
    - '64710'
  Población por municipio de residencia y edad simple según nacionalidad (española/extranjera) y sexo:
    id: '4'
    consultas:
    - '64670'
    - '64736'
    - '64737'
    - '64739'
    - '64740'
    - '64744'
  Población por municipio de residencia y lugar de nacimiento según grandes grupos de edad y sexo:
    id: '5'
    consultas:
    - '64683'
    - '64746'
    - '64747'
    - '64748'
  Población por municipio de residencia y país de nacimiento extranjero según sexo:
    id: '6'
    consultas:
    - '64685'
    - '64749'
    - '64750'
    - '64751'
variables:
- TEMPORAL
- TERRITORIO
- SEXO
- NACIONALIDAD
- EDAD
- INDICATOR
- OBS_VALUE
- FREQ
- RELAC_RESID_NAC
- LUG_NAC_PADRON
