NOMBRE_DSD: DSD_DEFCAU
categoria: HEALTH
grupos_consultas:
  Defunciones por causa de muerte (capítulos CIE 10ª), sexo y provincia de residencia:
    id: '1'
    consultas:
    - '65723'
  Defunciones por causa de muerte (lista reducida CIE 10ª), grupo de edad, sexo y mes de la defunción:
    id: '2'
    consultas:
    - '65971'
    - '65992'
    - '65993'
    - '65994'
    - '65995'
    - '65996'
    - '65998'
    - '65999'
    - '66000'
  Defunciones por covid-19 virus identificado y virus no identificado (sospechoso) según grupo de edad y sexo en Andalucía:
    id: '3'
    consultas:
    - '65724'
  ? Defunciones por covid-19 virus identificado y virus no identificado (sospechoso)
    según lugar de ocurrencia, mes de defunción y sexo en Andalucía
  : id: '4'
    consultas:
    - '60318'
variables:
- TEMPORAL
- CIE10
- TERRITORIO
- SEXO
- INDICATOR
- OBS_VALUE
- FREQ
- G102
- EDAD
- MES
- EDCA_LUGDEF
