NOMBRE_DSD: DSD_SOCMER
grupos_consultas:
  Sociedades mercantiles:
    consultas:
    - '65646'
    - '28098'
    id: '1'
  Sociedades mercantiles constituidas:
    consultas:
    - '497'
    - '65647'
    id: '2'
variables:
- TIME_PERIOD
- REF_AREA
- D_FORMA_JUR_SOCMER_0
- OBS_STATUS
- INDICATOR
- OBS_VALUE
- FREQ
- D_CNAE09_0
- D_SEXO_SOCIOS_0
