NOMBRE_DSD: DSD_DIRECTORIO
categoria: BUSINESS_STAT
grupos_consultas:
  Empresas por sector de actividad y municipio*:
    id: '1'
    consultas:
    - '65500'
    - '65467'
    - '65471'
    - '65474'
    - '65476'
    - '65477'
    - '65478'
    - '65458'
    - '65501'
    - '65502'
    - '65503'
    - '65504'
    - '65505'
    - '65506'
variables:
- TEMPORAL
- TERRITORIO
- CNAE09
- INDICATOR
- OBS_VALUE
- FREQ
