NOMBRE_DSD: DSD_CRA
categoria: LABOUR
grupos_consultas:
  Contabilidad Regional Anual de Andalucía. Revisión estadística 2019:
    id: '1'
    consultas:
    - '27050'
    - '27052'
    - '27053'
    - '27054'
    - '27055'
    - '66051'
  Contabilidad Regional Anual de Andalucía. Revi:
    id: '2'
    consultas:
    - '27051'
variables:
- MACROECO
- TEMPORAL
- OBS_STATUS
- TERRITORIO
- INDICATOR
- OBS_VALUE
- FREQ
- CNAE_O9_CRA_NEW
