NOMBRE_DSD: DSD_EEE
categoria: SECTORAL_STAT
grupos_consultas:
  Estadística Estructural de Empresas:
    id: '1'
    consultas:
    - '12267'
variables:
- TEMPORAL
- TIPO_ESTAB
- ACTIV_EST
- TERRITORIO
- INDICATOR
- OBS_VALUE
- FREQ
