NOMBRE_DSD: DSD_PENSIONES
grupos_consultas:
  Resultados municipales. Pensiones en alta:
    consultas:
    - '13302'
    - '13301'
    id: '1'
  Resultados municipales. Pensionistas en alta:
    consultas:
    - '13305'
    - '13304'
    id: '2'
variables:
- TIME_PERIOD
- REF_AREA
- D_CLASEDEPENSION_0
- INDICATOR
- OBS_VALUE
- FREQ
- SEXO
- EDAD
- D_PCSSA_JUBVIUDEDAD_0
