NOMBRE_DSD: DSD_PENSIONES
categoria: SOCIAL_PROTECT
grupos_consultas:
  Resultados municipales. Pensiones en alta:
    id: '1'
    consultas:
    - '13302'
    - '13301'
  Resultados municipales. Pensionistas en alta:
    id: '2'
    consultas:
    - '13305'
    - '13304'
variables:
- TEMPORAL
- TERRITORIO
- CLASEDEPENSION
- INDICATOR
- OBS_VALUE
- FREQ
- SEXO
- EDAD
- PCSSA_JUBVIUDEDAD
